// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using moneytor_api.DbContexts;

#nullable disable

namespace moneytor_api.Migrations
{
    [DbContext(typeof(MoneytorDbContext))]
    [Migration("20250627034033_IncomeAndExpensesUpdates")]
    partial class IncomeAndExpensesUpdates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("moneytor_api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("moneytor_api.Models.ExpenseCategoryModel", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BudgetCurrency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BudgetTypeCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DeductionTypeCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpenseTypeCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ionicon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("StandardBudgetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.HasIndex("BudgetTypeCode");

                    b.HasIndex("DeductionTypeCode");

                    b.HasIndex("ExpenseTypeCode");

                    b.ToTable("ExpenseCategory");
                });

            modelBuilder.Entity("moneytor_api.Models.MasterModels.BudgetTypeModel", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("ConversionValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("BudgetType");
                });

            modelBuilder.Entity("moneytor_api.Models.MasterModels.DeductionTypeModel", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("DeductionType");
                });

            modelBuilder.Entity("moneytor_api.Models.MasterModels.ExpenseTypeModel", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("ExpenseType");
                });

            modelBuilder.Entity("moneytor_api.Models.MasterModels.FundSourceModel", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ionicon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("FundSource");
                });

            modelBuilder.Entity("moneytor_api.Models.TransactionModels.ExpenseModel", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpenseCategoryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExpenseTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ionicon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Remarks")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.HasIndex("ExpenseCategoryCode");

                    b.HasIndex("ExpenseTypeCode");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("moneytor_api.Models.TransactionModels.IncomeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Remarks")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Income");
                });

            modelBuilder.Entity("moneytor_api.Models.ExpenseCategoryModel", b =>
                {
                    b.HasOne("moneytor_api.Models.MasterModels.BudgetTypeModel", "BudgetType")
                        .WithMany()
                        .HasForeignKey("BudgetTypeCode");

                    b.HasOne("moneytor_api.Models.MasterModels.DeductionTypeModel", "DeductionType")
                        .WithMany()
                        .HasForeignKey("DeductionTypeCode");

                    b.HasOne("moneytor_api.Models.MasterModels.ExpenseTypeModel", "ExpenseType")
                        .WithMany()
                        .HasForeignKey("ExpenseTypeCode");

                    b.Navigation("BudgetType");

                    b.Navigation("DeductionType");

                    b.Navigation("ExpenseType");
                });

            modelBuilder.Entity("moneytor_api.Models.TransactionModels.ExpenseModel", b =>
                {
                    b.HasOne("moneytor_api.Models.ExpenseCategoryModel", "ExpenseCategory")
                        .WithMany()
                        .HasForeignKey("ExpenseCategoryCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("moneytor_api.Models.MasterModels.ExpenseTypeModel", "ExpenseType")
                        .WithMany()
                        .HasForeignKey("ExpenseTypeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseCategory");

                    b.Navigation("ExpenseType");
                });
#pragma warning restore 612, 618
        }
    }
}
